import { getCopy } from "@/i18n/server";
import { MarketingHeader } from "@/components/marketing-header";
import { AnimatedStats } from "@/components/animated-stats";
import Link from "next/link";
import { EditorialFloatIcons } from "@/components/editorial-float-icons";
import { ScrollIconField } from "@/components/scroll-icon-field";
import { ProductCustomizer } from "@/components/product-customizer";
import { ProductGrid } from "@/components/product-grid";
import { ContactForm } from "@/components/contact-form";
import { ClothingRequestModal } from "@/components/clothing-request-modal";
import { getSession, isAdminSession } from "@/lib/auth";
import { listStudioServices } from "@/lib/services";

const projects = [
  { published: true, number: "01", label: "vedoyassist.no", name: "Vedøy Assist", text: "Teknologihjelp laget for å være trygg, enkel og personlig.", tag: "IT / SERVICE", className: "project-card--mint", href: "/projects/assist", image: "/projects/vedoy-assist.png", imageAlt: "Vedøy Assist" },
  { published: true, number: "02", label: "vedoycollective.no", name: "Vedøy Collective", text: "Nettbutikk, kolleksjoner og merkevare bygget for videre vekst.", tag: "COMMERCE / BRAND", className: "project-card--sand", href: "/projects/collective", image: "/projects/vedoy-collective.jfif", imageAlt: "Vedøy Collective-prosjekt" },
  { published: true, number: "03", label: "BETA · VEDØY LAB", name: "Omnicart Tycoon", text: "E-commerce simulator for produktvalg, lager, ordre og vekst.", tag: "SIMULATOR / COMMERCE", className: "project-card--omni", href: "/projects/omnicart-tycoon", image: "/projects/omnicart-tycoon.jfif", imageAlt: "Omnicart Tycoon e-commerce simulator" }
];
const steps = [["01", "Fortell", "Beskriv målet eller problemet. Det trenger ikke være teknisk."], ["02", "Avklar", "Vi foreslår løsning, omfang og pris før noe blir bindende."], ["03", "Bygg", "Design og utvikling skjer i tydelige steg med demo underveis."], ["04", "Lanser", "Vi hjelper med publisering, domene, drift og videre forbedringer."]];

export const dynamic = "force-dynamic";

export default async function HomePage() {
  const c = await getCopy();
 const [studioServices, session] = await Promise.all([listStudioServices(), getSession()]); const isAdministrator = isAdminSession(session); return <>
  <section className="editorial-hero"><MarketingHeader initialProfile={session ? { name: session.name, avatarUrl: session.avatarUrl } : null} /><div className="hero-orbit" /><div className="hero-copy"><p className="editorial-kicker">{c("VEDØY STUDIO · HAUGESUND · DIGITALT")}</p><h1>{c("Vi bygger det")}<br />{c("bedriften din")}<br /><em>{c("trenger.")}</em></h1><p className="hero-intro">{c("Nettsider, apper, nettbutikk, hosting, design, profilprodukter og trykk — samlet hos én partner.")}</p><div className="hero-actions"><Link href="#kontakt" className="editorial-button">{c("Fortell oss hva du trenger")} <span>↗</span></Link><a href="#prosjekter" className="editorial-outline">{c("Se prosjekter")}</a></div></div><div className="hero-status"><i /> {c("Tilgjengelig for nye prosjekter")}</div><EditorialFloatIcons variant="hero" /><div className="ticker"><div className="ticker-track"><span>{c("SHOPIFY · HOSTING · DOMENE · DESIGN · TRYKK · ARTIST · KUNST · PROFILPRODUKTER · NETTSIDER · WEBAPPER ·")}</span><span aria-hidden="true">{c("SHOPIFY · HOSTING · DOMENE · DESIGN · TRYKK · ARTIST · KUNST · PROFILPRODUKTER · NETTSIDER · WEBAPPER ·")}</span></div></div></section>
  <AnimatedStats projects={projects.filter(project => project.published).length} services={studioServices.filter(service => service.slug !== "ecommerce" && service.published !== false).length} />
  <section className="intro-section"><div className="section-number">01</div><div><p className="editorial-kicker lime">{c("ET STUDIO SOM KAN BYGGE, PROFILERE OG DRIFTE")}</p><h2>{c("Fra første idé")}<br />{c("til bedriften er")} <em>{c("synlig.")}</em></h2></div><div className="intro-section__copy"><p>{c("Vedøy Studio samler nettsider, nettbutikker, web-apper, hosting og drift, design og profilering — også klær med logo, trykksaker og produkter for artister og kunstnere. Du får én partner fra idé og visuell retning til lansering, produksjon og videre vekst.")}</p><div className="intro-section__services" aria-label={c("Dette tilbyr Vedøy Studio")}><span>{c("Nettsider")}</span><span>{c("Web-apper")}</span><span>{c("Nettbutikk")}</span><span>{c("Hosting")}</span><span>{c("Klær med logo")}</span><span>{c("Trykk")}</span><span>{c("Artist & merch")}</span><span>{c("Kunstprodukter")}</span></div></div><a href="#tjenester" className="section-next-link" aria-label={c("Gå til neste seksjon: tjenester")}><span>{c("NESTE · TJENESTER")}</span><b aria-hidden="true">↓</b></a></section>
  <ScrollIconField variant="mixed" />
  <section className="services-section" id="tjenester"><div className="section-heading-dark"><div className="section-heading-dark__topline"><p className="editorial-kicker lime">{c("02 · TJENESTER")}</p>{isAdministrator ? <Link href="/studio/services?new=1" className="services-admin-add" aria-label={c("Legg til ny tjeneste")} title={c("Legg til ny tjeneste")}>+</Link> : null}</div><h2>{c("Én partner.")}<br /><em>{c("Flere muligheter.")}</em></h2><p className="section-heading-dark__intro">{c("Alle kort åpner en egen tjenesteside med informasjon, ca-priser, felles bedriftsabonnementer og mulighet for oppgradering. Pris, leverandør, omfang og levering avklares før du godkjenner.")}</p></div><div className="services-grid">{studioServices.map((service) => <Link href={`/tjenester/${service.slug}`} className="service-card is-live" key={service.slug}><small>{service.number}</small><span className="service-card__status">{c(service.slug === "ecommerce" ? "DEMO" : "BESTILL NÅ")}</span><h3>{c(service.title)}</h3><p>{c(service.cardText)}</p><div className="service-card__structure"><span>{c("INFO")}</span><span>{c("CA-PRIS")}</span><span>{c("ABONNEMENT")}</span></div><b>{c(service.slug === "hosting-og-domene" ? "Åpne side og bestilling →" : "Åpne tjenesteside →")}</b></Link>)}</div></section>
  <ScrollIconField variant="network" />
  <section className="ecosystem-section" id="plattform"><div className="ecosystem-heading"><div><p className="editorial-kicker">{c("03 · VEDØY-ØKOSYSTEMET")}</p><h2>{c("Bygg. Drift. Voks.")}<br /><em>{c("Utvikle.")}</em></h2></div><p>{c("Én plattform kan ikke gjøre alt på én dag. Derfor viser vi tydelig hva som er publisert, i beta eller planlagt — men alt følger samme språk og samme konto.")}</p></div><ProductGrid /><aside className="discord-event-promo"><div><small>{c("FELLESSKAP · DISCORD EVENT")}</small><h3>{c("Bli med når Vedøy bygges videre.")}</h3><p>{c("En lavterskel samling for deg som vil følge utviklingen, stille spørsmål eller se hva som kommer i Vedøy-økosystemet.")}</p></div><a href="https://discord.gg/aBbPzsWZ?event=1547558121273032724" target="_blank" rel="noreferrer">{c("Åpne Discord-event")} <span>↗</span></a></aside></section>
    <section className="projects-section" id="prosjekter"><div className="section-heading-dark"><p className="editorial-kicker lime">{c("04 · PROSJEKTER")}</p><h2>{c("Det beste beviset er")}<br /><em>{c("det vi bygger.")}</em></h2></div><div className="projects-grid">{projects.map((project) => <Link href={project.href} className={`project-card ${project.className}`} key={project.name}><div className="project-card__visual"><img src={project.image} alt={project.imageAlt} /><div className="project-card__visual-content"><small>{project.label}</small><strong>{project.name.replace("Vedøy ", "")}</strong><span className="project-card__button">{c("LES OM PROSJEKTET ↗")}</span></div></div><div className="project-card__copy"><small>{project.number}</small><h3>{project.name}</h3><p>{c(project.text)}</p><span>{project.tag}</span></div></Link>)}</div></section>
  <ScrollIconField variant="orbit" />
  <section className="hosting-section" id="hosting"><div><p className="editorial-kicker lime">{c("05 · HOSTING + FULLSTACK · BESTILL NÅ")}</p><h2>{c("Vi bygger.")}<br />{c("Vi kan også")}<br /><em>{c("holde det på.")}</em></h2><p>{c("Bestill hosting, web-apper, nettbutikker og andre fullstack-apper med rammeverk som passer prosjektet — for eksempel Next.js, React, Vue, Node eller Shopify.")}</p><p className="hosting-section__note"><strong>{c("Trygg bestilling:")}</strong> {c("Du sender en forespørsel, ikke en automatisk betaling. Vi avklarer løsning, leverandør, pris og levering før noe kjøpes eller registreres.")}</p><Link href="/tjenester/hosting-og-domene#konfigurer-hosting" className="editorial-button">{c("Bestill hosting")} <span>↗</span></Link></div><div className="infra-panel"><header><span><i /> {c("VEDØY INFRA / KONFIGURER")}</span><b>{c("BESTILL NÅ")}</b></header><div className="infra-map"><span className="infra-node node-ssl">{c("SSL")}<small>{c("KLART")}</small></span><span className="infra-node node-backup">{c("BACKUP")}<small>{c("VALGBART")}</small></span><span className="infra-node node-dns">{c("DNS")}<small>{c("AVKLARES")}</small></span><span className="infra-node node-client">{c("KUNDE")}<small>{c("nettleser")}</small></span><span className="infra-node node-edge">{c("EDGE")}<small>{c("Vercel")}</small></span><span className="infra-node node-app">{c("APP")}<small>{c("Next.js")}</small></span><span className="infra-node node-data">{c("DATA")}<small>{c("sikker")}</small></span></div></div><EditorialFloatIcons variant="hosting" /></section>
  <section className="products-section" id="profilprodukter"><div className="products-copy"><p className="editorial-kicker lime">{c("06 · PROFILPRODUKTER")}</p><h2>{c("Bedriften på skjermen.")}<br />{c("Og ute i")} <em>{c("verden.")}</em></h2><p>{c("Last opp logoen din og se en rask visualisering på utvalgte plagg. Vi hjelper med produktvalg, plassering, design og produksjon.")}</p><div className="products-copy__actions"><Link href="/tjenester/profilprodukter#bestill-profilprodukter" className="dark-button">{c("Åpne bestillingsskjema")} <span>↗</span></Link><ClothingRequestModal /></div></div><ProductCustomizer showRequestForm={false} /></section>
  <section className="process-section"><div className="section-heading-dark"><p className="editorial-kicker lime">{c("07 · SLIK JOBBER VI")}</p><h2>{c("Enkelt å starte.")}<br /><em>{c("Tydelig hele veien.")}</em></h2></div><div className="steps-grid">{steps.map(([number, title, text]) => <article key={number}><small>{number}</small><h3>{c(title)}</h3><p>{c(text)}</p></article>)}</div></section>
  <section className="contact-section" id="kontakt"><div><p className="editorial-kicker lime">{c("BESTILL NETTSIDE ELLER HOSTING")}</p><h2>{c("Hva skal vi")}<br /><em>{c("bygge?")}</em></h2><p>{c("Nettsider og hosting kan bestilles nå. Web-apper, nettbutikker og fullstack-løsninger avklarer vi sammen før levering.")}</p><Link href="/booking" className="editorial-button contact-booking-button">{c("Bestill time")} <span>↗</span></Link><a href="mailto:leander@vedoystudio.no" className="contact-link">{c("leander@vedoystudio.no")}</a><a href="tel:+4745917041" className="contact-link">459 17 041</a><span className="contact-link">{c("Haugesund, Norge")}</span></div><ContactForm /></section>
  <footer className="editorial-footer"><div><img src="/imgs/Logos/Vedoy_Logo_W.png" alt="Vedøy Studio" /><p>{c("Nettsider, apper og digitale løsninger fra Haugesund — for bedrifter som vil videre.")}</p><Link href="/login?next=/studio/requests" className="footer-admin-link">{c("Administrator")}</Link></div><div><small>{c("FELLESSKAP")}</small><a href="https://discord.gg/aBbPzsWZ?event=1547558121273032724" target="_blank" rel="noreferrer">{c("Vedøy Discord event ↗")}</a><a href="/developers">{c("Vedøy Developers")}</a><a href="mailto:leander@vedoystudio.no">{c("leander@vedoystudio.no")}</a><a href="tel:+4745917041">459 17 041</a><span>{c("© 2026 VEDØY STUDIO · ORG.NR. 937 024 622")}</span><span className="app-version">{c("v0.1.0 · Beta")}</span></div></footer>
</>; }
