import Link from "next/link";
import { EditorialFloatIcons } from "@/components/editorial-float-icons";
import { ScrollIconField } from "@/components/scroll-icon-field";
import { ProductCustomizer } from "@/components/product-customizer";
import { ProductGrid } from "@/components/product-grid";
import { ContactForm } from "@/components/contact-form";
import { ClothingRequestModal } from "@/components/clothing-request-modal";
import { studioServices } from "@/lib/services";

const projects = [
  { number: "01", label: "vedoyassist.no", name: "Vedøy Assist", text: "Teknologihjelp laget for å være trygg, enkel og personlig.", tag: "IT / SERVICE", className: "project-card--mint", href: "/projects/assist", image: "/projects/vedoy-assist.png", imageAlt: "Vedøy Assist" },
  { number: "02", label: "vedoycollective.no", name: "Vedøy Collective", text: "Nettbutikk, kolleksjoner og merkevare bygget for videre vekst.", tag: "COMMERCE / BRAND", className: "project-card--sand", href: "/projects/collective", image: "/projects/vedoy-collective.jfif", imageAlt: "Vedøy Collective-prosjekt" },
  { number: "03", label: "BETA · VEDØY LAB", name: "Omnicart Tycoon", text: "E-commerce simulator for produktvalg, lager, ordre og vekst.", tag: "SIMULATOR / COMMERCE", className: "project-card--omni", href: "/projects/omnicart-tycoon", image: "/projects/omnicart-tycoon.jfif", imageAlt: "Omnicart Tycoon e-commerce simulator" }
];
const steps = [["01", "Fortell", "Beskriv målet eller problemet. Det trenger ikke være teknisk."], ["02", "Avklar", "Vi foreslår løsning, omfang og pris før noe blir bindende."], ["03", "Bygg", "Design og utvikling skjer i tydelige steg med demo underveis."], ["04", "Lanser", "Vi hjelper med publisering, domene, drift og videre forbedringer."]];

function Header() { return <header className="editorial-header"><Link href="/" className="editorial-logo"><img src="/imgs/Logos/Vedoy_Logo_W.png" alt="Vedøy" /></Link><nav><a href="#tjenester">Tjenester</a><a href="#plattform">Plattform</a><a href="#prosjekter">Prosjekter</a><a href="#profilprodukter">Bedriftsklær</a><a href="#kontakt">Kontakt</a></nav><Link href="/booking" className="editorial-cta">Bestill time <span>↗</span></Link></header>; }
export default function HomePage() { return <>
  <section className="editorial-hero"><Header /><div className="hero-orbit" /><div className="hero-copy"><p className="editorial-kicker">VEDØY STUDIO · HAUGESUND · DIGITALT</p><h1>Vi bygger det<br />bedriften din<br /><em>trenger.</em></h1><p className="hero-intro">Nettsider, apper, nettbutikk, hosting, design, profilprodukter og trykk — samlet hos én partner.</p><div className="hero-actions"><Link href="#kontakt" className="editorial-button">Fortell oss hva du trenger <span>↗</span></Link><a href="#prosjekter" className="editorial-outline">Se prosjekter</a></div></div><div className="hero-status"><i /> Tilgjengelig for nye prosjekter</div><EditorialFloatIcons variant="hero" /><div className="ticker"><div className="ticker-track"><span>SHOPIFY · HOSTING · DOMENE · DESIGN · TRYKK · ARTIST · KUNST · PROFILPRODUKTER · NETTSIDER · WEBAPPER ·</span><span aria-hidden="true">SHOPIFY · HOSTING · DOMENE · DESIGN · TRYKK · ARTIST · KUNST · PROFILPRODUKTER · NETTSIDER · WEBAPPER ·</span></div></div></section>
  <section className="intro-section"><div className="section-number">01</div><div><p className="editorial-kicker lime">ET STUDIO SOM KAN BYGGE, PROFILERE OG DRIFTE</p><h2>Fra første idé<br />til bedriften er <em>synlig.</em></h2></div><div className="intro-section__copy"><p>Vedøy Studio samler nettsider, nettbutikker, web-apper, hosting og drift, design og profilering — også klær med logo, trykksaker og produkter for artister og kunstnere. Du får én partner fra idé og visuell retning til lansering, produksjon og videre vekst.</p><div className="intro-section__services" aria-label="Dette tilbyr Vedøy Studio"><span>Nettsider</span><span>Web-apper</span><span>Nettbutikk</span><span>Hosting</span><span>Klær med logo</span><span>Trykk</span><span>Artist & merch</span><span>Kunstprodukter</span></div></div><a href="#tjenester" className="section-next-link" aria-label="Gå til neste seksjon: tjenester"><span>NESTE · TJENESTER</span><b aria-hidden="true">↓</b></a></section>
  <ScrollIconField variant="mixed" />
  <section className="services-section" id="tjenester"><div className="section-heading-dark"><p className="editorial-kicker lime">02 · TJENESTER</p><h2>Én partner.<br /><em>Flere muligheter.</em></h2><p className="section-heading-dark__intro">Alle kort åpner en egen tjenesteside med informasjon, ca-priser, felles bedriftsabonnementer og mulighet for oppgradering. Pris, leverandør, omfang og levering avklares før du godkjenner.</p></div><div className="services-grid">{studioServices.map((service) => <Link href={`/tjenester/${service.slug}`} className="service-card is-live" key={service.slug}><small>{service.number}</small><span className="service-card__status">BESTILL NÅ</span><h3>{service.title}</h3><p>{service.cardText}</p><div className="service-card__structure"><span>INFO</span><span>CA-PRIS</span><span>ABONNEMENT</span></div><b>{service.slug === "hosting-og-domene" ? "Åpne side og bestilling →" : "Åpne tjenesteside →"}</b></Link>)}</div></section>
  <ScrollIconField variant="network" />
  <section className="ecosystem-section" id="plattform"><div className="ecosystem-heading"><div><p className="editorial-kicker">03 · VEDØY-ØKOSYSTEMET</p><h2>Bygg. Drift. Voks.<br /><em>Utvikle.</em></h2></div><p>Én plattform kan ikke gjøre alt på én dag. Derfor viser vi tydelig hva som er publisert, i beta eller planlagt — men alt følger samme språk og samme konto.</p></div><ProductGrid /></section>
    <section className="projects-section" id="prosjekter"><div className="section-heading-dark"><p className="editorial-kicker lime">04 · PROSJEKTER</p><h2>Det beste beviset er<br /><em>det vi bygger.</em></h2></div><div className="projects-grid">{projects.map((project) => <Link href={project.href} className={`project-card ${project.className}`} key={project.name}><div className="project-card__visual"><img src={project.image} alt={project.imageAlt} /><div className="project-card__visual-content"><small>{project.label}</small><strong>{project.name.replace("Vedøy ", "")}</strong><span className="project-card__button">LES OM PROSJEKTET ↗</span></div></div><div className="project-card__copy"><small>{project.number}</small><h3>{project.name}</h3><p>{project.text}</p><span>{project.tag}</span></div></Link>)}</div></section>
  <ScrollIconField variant="orbit" />
  <section className="hosting-section" id="hosting"><div><p className="editorial-kicker lime">05 · HOSTING + FULLSTACK · BESTILL NÅ</p><h2>Vi bygger.<br />Vi kan også<br /><em>holde det på.</em></h2><p>Bestill hosting, web-apper, nettbutikker og andre fullstack-apper med rammeverk som passer prosjektet — for eksempel Next.js, React, Vue, Node eller Shopify.</p><p className="hosting-section__note"><strong>Trygg bestilling:</strong> Du sender en forespørsel, ikke en automatisk betaling. Vi avklarer løsning, leverandør, pris og levering før noe kjøpes eller registreres.</p><Link href="/tjenester/hosting-og-domene#konfigurer-hosting" className="editorial-button">Bestill hosting <span>↗</span></Link></div><div className="infra-panel"><header><span><i /> VEDØY INFRA / KONFIGURER</span><b>BESTILL NÅ</b></header><div className="infra-map"><span className="infra-node node-ssl">SSL<small>KLART</small></span><span className="infra-node node-backup">BACKUP<small>VALGBART</small></span><span className="infra-node node-dns">DNS<small>AVKLARES</small></span><span className="infra-node node-client">KUNDE<small>nettleser</small></span><span className="infra-node node-edge">EDGE<small>Vercel</small></span><span className="infra-node node-app">APP<small>Next.js</small></span><span className="infra-node node-data">DATA<small>sikker</small></span></div></div><EditorialFloatIcons variant="hosting" /></section>
  <section className="products-section" id="profilprodukter"><div className="products-copy"><p className="editorial-kicker lime">06 · PROFILPRODUKTER</p><h2>Bedriften på skjermen.<br />Og ute i <em>verden.</em></h2><p>Last opp logoen din og se en rask visualisering på utvalgte plagg. Vi hjelper med produktvalg, plassering, design og produksjon.</p><div className="products-copy__actions"><Link href="/tjenester/profilprodukter#bestill-profilprodukter" className="dark-button">Åpne bestillingsskjema <span>↗</span></Link><ClothingRequestModal /></div></div><ProductCustomizer showRequestForm={false} /></section>
  <section className="process-section"><div className="section-heading-dark"><p className="editorial-kicker lime">07 · SLIK JOBBER VI</p><h2>Enkelt å starte.<br /><em>Tydelig hele veien.</em></h2></div><div className="steps-grid">{steps.map(([number, title, text]) => <article key={number}><small>{number}</small><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="contact-section" id="kontakt"><div><p className="editorial-kicker lime">BESTILL NETTSIDE ELLER HOSTING</p><h2>Hva skal vi<br /><em>bygge?</em></h2><p>Nettsider og hosting kan bestilles nå. Web-apper, nettbutikker og fullstack-løsninger avklarer vi sammen før levering.</p><Link href="/booking" className="editorial-button contact-booking-button">Bestill time <span>↗</span></Link><a href="mailto:leander@vedoystudio.no" className="contact-link">leander@vedoystudio.no</a><a href="tel:+4745917041" className="contact-link">459 17 041</a><span className="contact-link">Haugesund, Norge</span></div><ContactForm /></section>
  <footer className="editorial-footer"><div><img src="/imgs/Logos/Vedoy_Logo_W.png" alt="Vedøy Studio" /><p>Nettsider, apper og digitale løsninger fra Haugesund — for bedrifter som vil videre.</p><Link href="/login?next=/studio/requests" className="footer-admin-link">Administrator</Link></div><div><a href="mailto:leander@vedoystudio.no">leander@vedoystudio.no</a><a href="tel:+4745917041">459 17 041</a><span>© 2026 VEDØY STUDIO · ORG.NR. 937 024 622</span><span className="app-version">v0.1.0 · Beta</span></div></footer>
</>; }
