import Link from "next/link";
import { EditorialFloatIcons } from "@/components/editorial-float-icons";
import { ScrollIconField } from "@/components/scroll-icon-field";
import { ProductCustomizer } from "@/components/product-customizer";
import { ProductGrid } from "@/components/product-grid";
import { ContactForm } from "@/components/contact-form";
import { ClothingRequestModal } from "@/components/clothing-request-modal";
import { studioServices } from "@/lib/services";

const projects = [
  { number: "01", label: "vedoyassist.no", name: "Vedøy Assist", text: "Teknologihjelp laget for å være trygg, enkel og personlig.", tag: "IT / SERVICE", className: "project-card--mint", href: "https://vedoyassist.no", image: "/projects/vedoy-assist.png", imageAlt: "Vedøy Assist" },
  { number: "02", label: "vedoycollective.no", name: "Vedøy Collective", text: "Nettbutikk, kolleksjoner og merkevare bygget for videre vekst.", tag: "COMMERCE / BRAND", className: "project-card--sand", href: "https://vedoycollective.no", image: "/projects/vedoy-collective.jfif", imageAlt: "Vedøy Collective-prosjekt" },
  { number: "03", label: "KOMMER SNART", name: "Vedøy Hosting", text: "Hostingflyt med drift, domene og support i samme opplevelse. Tjenesten er under utvikling og åpner snart.", tag: "PLANLAGT · FULL-STACK / CLOUD", className: "project-card--green", href: "/tjenester/hosting-og-domene#konfigurer-hosting", image: "/imgs/Logos/vedoy-growth-logo_white.png", imageAlt: "Vedøy Hosting kommer snart" }
];
const steps = [["01", "Fortell", "Beskriv målet eller problemet. Det trenger ikke være teknisk."], ["02", "Avklar", "Vi foreslår løsning, omfang og pris før noe blir bindende."], ["03", "Bygg", "Design og utvikling skjer i tydelige steg med demo underveis."], ["04", "Lanser", "Vi hjelper med publisering, domene, drift og videre forbedringer."]];

function Header() { return <header className="editorial-header"><Link href="/" className="editorial-logo"><img src="/imgs/Logos/Vedoy_Logo_W.png" alt="Vedøy" /></Link><nav><a href="#tjenester">Tjenester</a><a href="#plattform">Plattform</a><a href="#prosjekter">Prosjekter</a><a href="#profilprodukter">Bedriftsklær</a><a href="#kontakt">Kontakt</a></nav><Link href="/booking" className="editorial-cta">Bestill time <span>↗</span></Link></header>; }
export default function HomePage() { return <>
  <section className="editorial-hero"><Header /><div className="hero-orbit" /><div className="hero-copy"><p className="editorial-kicker">VEDØY STUDIO · HAUGESUND · DIGITALT</p><h1>Vi bygger det<br />bedriften din<br /><em>trenger.</em></h1><p className="hero-intro">Nettsider, apper, nettbutikk, hosting og design — profesjonelt utviklet uten unødvendig teknisk rot.</p><div className="hero-actions"><Link href="#kontakt" className="editorial-button">Fortell oss hva du trenger <span>↗</span></Link><a href="#prosjekter" className="editorial-outline">Se prosjekter</a></div></div><div className="hero-status"><i /> Tilgjengelig for nye prosjekter</div><EditorialFloatIcons variant="hero" /><div className="ticker"><div className="ticker-track"><span>SHOPIFY · HOSTING · DOMENE · DESIGN · SEO · PROFILPRODUKTER · NEXT.JS · AUTOMATISERING · NETTSIDER · WEBAPPER ·</span><span aria-hidden="true">SHOPIFY · HOSTING · DOMENE · DESIGN · SEO · PROFILPRODUKTER · NEXT.JS · AUTOMATISERING · NETTSIDER · WEBAPPER ·</span></div></div></section>
  <section className="intro-section"><div className="section-number">01</div><div><p className="editorial-kicker lime">ET STUDIO SOM KAN BYGGE OG DRIFTE</p><h2>Fra første skisse<br />til løsningen er <em>live.</em></h2></div><p>Vedøy Studio kombinerer design og utvikling, så bedriften kan forholde seg til én partner. Vi kan starte lite, bygge modulært og utvide når behovet faktisk kommer.</p></section>
  <ScrollIconField variant="mixed" />
  <section className="services-section" id="tjenester"><div className="section-heading-dark"><p className="editorial-kicker lime">02 · TJENESTER</p><h2>Én partner.<br /><em>Flere muligheter.</em></h2></div><div className="services-grid">{studioServices.map((service) => { const live = service.slug === "nettsider"; return <Link href={live ? "/#kontakt" : `/tjenester/${service.slug}`} className={`service-card ${live ? "is-live" : "is-coming"}`} key={service.slug}><small>{service.number}</small><span className="service-card__status">{live ? "BESTILL NÅ" : "KOMMER SNART"}</span><h3>{service.title}</h3><p>{service.cardText}</p><b>{live ? "Bestill nettside →" : "Se forhåndsvisning →"}</b></Link>; })}</div></section>
  <ScrollIconField variant="network" />
  <section className="ecosystem-section" id="plattform"><div className="ecosystem-heading"><div><p className="editorial-kicker">03 · VEDØY-ØKOSYSTEMET</p><h2>Bygg. Drift. Voks.<br /><em>Utvikle.</em></h2></div><p>Én plattform kan ikke gjøre alt på én dag. Derfor viser vi tydelig hva som er publisert, i beta eller planlagt — men alt følger samme språk og samme konto.</p></div><ProductGrid /></section>
  <section className="projects-section" id="prosjekter"><div className="section-heading-dark"><p className="editorial-kicker lime">04 · PROSJEKTER</p><h2>Det beste beviset er<br /><em>det vi bygger.</em></h2></div><div className="projects-grid">{projects.map((project) => <a href={project.href} target={project.href.startsWith("http") ? "_blank" : undefined} rel="noreferrer" className={`project-card ${project.className}`} key={project.name}><div className="project-card__visual"><img src={project.image} alt={project.imageAlt} /><div className="project-card__visual-content"><small>{project.label}</small><strong>{project.name === "Vedøy Hosting" ? "Hosting" : project.name.replace("Vedøy ", "")}</strong><button>{project.name === "Vedøy Hosting" ? "KONFIGURER HOSTING ↗" : "ÅPNE PROSJEKT ↗"}</button></div></div><div className="project-card__copy"><small>{project.number}</small><h3>{project.name}</h3><p>{project.text}</p><span>{project.tag}</span></div></a>)}</div></section>
  <ScrollIconField variant="orbit" />
  <section className="hosting-section" id="hosting"><div><p className="editorial-kicker lime">05 · HOSTING + DOMENE · KOMMER SNART</p><h2>Vi bygger.<br />Vi kan også<br /><em>holde det på.</em></h2><p>Vedøy Hosting er under utvikling. Når tjenesten åpner, kan Vedøy håndtere publisering, SSL, DNS, backup og teknisk drift med én fast kontakt.</p><Link href="/tjenester/hosting-og-domene" className="editorial-button">Se forhåndsvisning <span>↗</span></Link></div><div className="infra-panel"><header><span><i /> VEDØY INFRA / FORHÅNDSVISNING</span><b>SNART</b></header><div className="infra-map"><span className="infra-node node-ssl">SSL<small>PLANLAGT</small></span><span className="infra-node node-backup">BACKUP<small>PLANLAGT</small></span><span className="infra-node node-dns">DNS<small>PLANLAGT</small></span><span className="infra-node node-client">KUNDE<small>nettleser</small></span><span className="infra-node node-edge">EDGE<small>planlagt</small></span><span className="infra-node node-app">APP<small>Next.js</small></span><span className="infra-node node-data">DATA<small>sikker</small></span></div></div><EditorialFloatIcons variant="hosting" /></section>
  <section className="products-section" id="profilprodukter"><div className="products-copy"><p className="editorial-kicker lime">06 · PROFILPRODUKTER</p><h2>Bedriften på skjermen.<br />Og ute i <em>verden.</em></h2><p>Last opp logoen din og se en rask visualisering på utvalgte plagg. Vi hjelper med produktvalg, plassering, design og produksjon.</p><div className="products-copy__actions"><Link href="/tjenester/profilprodukter" className="dark-button">Se profilprodukter <span>↗</span></Link><ClothingRequestModal /></div></div><ProductCustomizer showRequestForm={false} /></section>
  <section className="process-section"><div className="section-heading-dark"><p className="editorial-kicker lime">07 · SLIK JOBBER VI</p><h2>Enkelt å starte.<br /><em>Tydelig hele veien.</em></h2></div><div className="steps-grid">{steps.map(([number, title, text]) => <article key={number}><small>{number}</small><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="contact-section" id="kontakt"><div><p className="editorial-kicker lime">BESTILL NETTSIDE</p><h2>Hva skal vi<br /><em>bygge?</em></h2><p>Nettsider kan bestilles nå. Andre tjenester er forhåndsvisninger og blir tydelig merket «Kommer snart».</p><Link href="/booking" className="editorial-button contact-booking-button">Bestill time <span>↗</span></Link><a href="mailto:leander@vedoystudio.no" className="contact-link">leander@vedoystudio.no</a><a href="tel:+4745917041" className="contact-link">459 17 041</a><span className="contact-link">Haugesund, Norge</span></div><ContactForm /></section>
  <footer className="editorial-footer"><div><img src="/imgs/Logos/Vedoy_Logo_W.png" alt="Vedøy Studio" /><p>Nettsider, apper og digitale løsninger fra Haugesund — for bedrifter som vil videre.</p><Link href="/login?next=/studio/requests" className="footer-admin-link">Administrator</Link></div><div><a href="mailto:leander@vedoystudio.no">leander@vedoystudio.no</a><a href="tel:+4745917041">459 17 041</a><span>© 2026 VEDØY STUDIO · ORG.NR. 937 024 622</span></div></footer>
</>; }
