"use client";

import { useState } from "react";

export function DomainEmailOrderForm() {
  const [form, setForm] = useState({ companyName: "", contactName: "", contactEmail: "", phone: "", domain: "", domainMode: "new", mailboxCount: 1, requestedAddresses: "", emailPackage: "standard", notes: "", website: "" });
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setMessage("");
    try {
      const response = await fetch("/api/domain-email-orders", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, requestedAddresses: form.requestedAddresses.split(/[\n,]/).map((address) => address.trim()).filter(Boolean) }) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error || "Bestillingen kunne ikke lagres.");
      setMessage(`Bestilling ${data.order.id} er mottatt. Domenet og e-posten er ikke kjøpt eller aktivert ennå — Vedøy bekrefter leveranse og pris først.`);
    } catch (error) { setMessage(error instanceof Error ? error.message : "Noe gikk galt. Prøv igjen."); }
    finally { setSaving(false); }
  }
  return <form className="domain-order-form" onSubmit={submit}><div className="company-setup-fields"><label>Bedriftsnavn<input required value={form.companyName} onChange={(event) => setForm({ ...form, companyName: event.target.value })} placeholder="Eksempel AS" /></label><label>Kontaktperson<input required value={form.contactName} onChange={(event) => setForm({ ...form, contactName: event.target.value })} placeholder="Fullt navn" /></label><label>E-post<input required type="email" value={form.contactEmail} onChange={(event) => setForm({ ...form, contactEmail: event.target.value })} placeholder="navn@bedrift.no" /></label><label>Telefon <span>valgfritt</span><input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} placeholder="47 00 00 00" /></label></div><div className="company-setup-fields"><label>Ønsket domene<input required value={form.domain} onChange={(event) => setForm({ ...form, domain: event.target.value })} placeholder="eksempel.no" /></label><label>Hva gjelder domenet?<select value={form.domainMode} onChange={(event) => setForm({ ...form, domainMode: event.target.value })}><option value="new">Nytt domene</option><option value="transfer">Flytt eksisterende domene</option><option value="existing">Bruk eksisterende domene</option></select></label><label>E-postpakke<select value={form.emailPackage} onChange={(event) => setForm({ ...form, emailPackage: event.target.value })}><option value="standard">E-post for bedrift</option><option value="none">Kun domene</option></select></label><label>Antall postbokser<input type="number" min="0" max="100" required value={form.mailboxCount} disabled={form.emailPackage === "none"} onChange={(event) => setForm({ ...form, mailboxCount: Number(event.target.value) })} /></label></div>{form.emailPackage === "standard" ? <label>Ønskede e-postadresser <span>én per linje eller separert med komma</span><textarea value={form.requestedAddresses} onChange={(event) => setForm({ ...form, requestedAddresses: event.target.value })} placeholder={"hei@eksempel.no\nnavn@eksempel.no"} /></label> : null}<label>Kommentar <span>valgfritt</span><textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} placeholder="For eksempel eksisterende leverandør, ønsket flyttedato eller behov." /></label><input className="company-honeypot" tabIndex={-1} autoComplete="off" value={form.website} onChange={(event) => setForm({ ...form, website: event.target.value })} aria-hidden="true" /><div className="company-setup-form__footer"><p><strong>På bestilling:</strong> Vedøy registrerer domenet og oppretter e-post manuelt hos Domeneshop etter at tilgjengelighet, leveranse og totalpris er bekreftet.</p><button className="editorial-button" disabled={saving}>{saving ? "Sender …" : "Send bestilling"} <span>↗</span></button></div>{message ? <p className="company-form-message" role="status">{message}</p> : null}</form>;
}
