"use client";

import { useState } from "react";
import type { CompanyRegistration, CompanyRegistrationStatus, DomainEmailOrder, ProvisioningRequestStatus } from "@/lib/types";

const companyStatusLabels: Record<CompanyRegistrationStatus, string> = { received: "Mottatt", reviewing: "Under vurdering", activated: "Aktivert", declined: "Avslått" };
const domainStatusLabels: Record<ProvisioningRequestStatus, string> = { received: "Mottatt", reviewing: "Sjekkes", ordered: "Bestilt hos leverandør", ready: "Klar", "needs-info": "Trenger info", cancelled: "Avbrutt" };
function formatDate(value: string) { return new Intl.DateTimeFormat("nb-NO", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }

export function CompanyOperations({ initialRegistrations, initialDomainOrders }: { initialRegistrations: CompanyRegistration[]; initialDomainOrders: DomainEmailOrder[] }) {
  const [registrations, setRegistrations] = useState(initialRegistrations); const [orders, setOrders] = useState(initialDomainOrders); const [notice, setNotice] = useState("");
  async function updateRegistration(id: string, status: CompanyRegistrationStatus) { const response = await fetch("/api/company-registrations", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status }) }); const data = await response.json(); if (!response.ok) return setNotice(data.error || "Kunne ikke oppdatere bedriften."); setRegistrations((items) => items.map((item) => item.id === id ? data.registration : item)); setNotice("Status er lagret."); }
  async function updateOrder(id: string, status: ProvisioningRequestStatus) { const response = await fetch("/api/domain-email-orders", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status }) }); const data = await response.json(); if (!response.ok) return setNotice(data.error || "Kunne ikke oppdatere bestillingen."); setOrders((items) => items.map((item) => item.id === id ? data.order : item)); setNotice("Status er lagret."); }
  return <section className="company-operations"><div className="company-operations__summary"><article><small>BEDRIFTER</small><strong>{registrations.length}</strong><span>Nye eller aktive oppsett</span></article><article><small>DOMENE OG E-POST</small><strong>{orders.length}</strong><span>Bestillinger å følge opp</span></article><article><small>SIKKERHET</small><strong>Manuell</strong><span>Ingen ekstern bestilling skjer automatisk</span></article></div><div className="company-operations__list"><section><header><small>BEDRIFTSREGISTRERINGER</small><h2>Nye arbeidsområder</h2></header>{registrations.length ? registrations.map((item) => <article key={item.id}><div><strong>{item.companyName}</strong><span>{item.ownerName} · {item.ownerTitle === "owner" ? "Eier" : "Daglig leder"}</span><a href={`mailto:${item.ownerEmail}`}>{item.ownerEmail}</a></div><dl><div><dt>Plan</dt><dd>{item.subscriptionPlan}</dd></div><div><dt>Seter</dt><dd>{item.invitedMembers.length + 1} av {item.seatLimit}</dd></div><div><dt>Team</dt><dd>{item.invitedMembers.length} planlagt</dd></div></dl><footer><time>{formatDate(item.createdAt)}</time><select value={item.status} aria-label={`Status for ${item.companyName}`} onChange={(event) => updateRegistration(item.id, event.target.value as CompanyRegistrationStatus)}>{Object.entries(companyStatusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></footer></article>) : <p className="request-empty">Ingen bedriftsregistreringer ennå.</p>}</section><section><header><small>DOMENE OG E-POST</small><h2>Til behandling hos Vedøy</h2></header>{orders.length ? orders.map((item) => <article key={item.id}><div><strong>{item.domain}</strong><span>{item.companyName} · {item.domainMode === "new" ? "Nytt domene" : item.domainMode === "transfer" ? "Flytt domene" : "Eksisterende domene"}</span><a href={`mailto:${item.contactEmail}`}>{item.contactName} · {item.contactEmail}</a></div><dl><div><dt>Postbokser</dt><dd>{item.mailboxCount}</dd></div><div><dt>Adresser</dt><dd>{item.requestedAddresses.length || "—"}</dd></div><div><dt>Leveranse</dt><dd>Manuell</dd></div></dl><footer><time>{formatDate(item.createdAt)}</time><select value={item.status} aria-label={`Status for ${item.domain}`} onChange={(event) => updateOrder(item.id, event.target.value as ProvisioningRequestStatus)}>{Object.entries(domainStatusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></footer></article>) : <p className="request-empty">Ingen domene- eller e-postbestillinger ennå.</p>}</section></div>{notice ? <p className="company-form-message" role="status">{notice}</p> : null}</section>;
}
