"use client";
import { useState } from "react";
import type { VedoyNewsPost } from "@/lib/types";
type Form = { title: string; excerpt: string; content: string; category: string; authorType: "user" | "vedi" };
const empty: Form = { title: "", excerpt: "", content: "", category: "Announcements", authorType: "user" };
export function NewsManager({ initialPosts, authorName, canPublish }: { initialPosts: VedoyNewsPost[]; authorName: string; authorAvatarUrl?: string; canPublish: boolean }) {
 const [posts,setPosts]=useState(initialPosts); const [form,setForm]=useState<Form>(empty); const [editingId,setEditingId]=useState<string|null>(null); const [message,setMessage]=useState(""); const set=(key:keyof Form,value:string)=>setForm(c=>({...c,[key]:value}));
 async function save(){const url=editingId?`/api/news/${editingId}`:"/api/news";const response=await fetch(url,{method:editingId?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const data=await response.json();if(!response.ok)return setMessage(data.error||"Kunne ikke lagre.");setPosts(editingId?posts.map(p=>p.id===editingId?data.post:p):[data.post,...posts]);setForm(empty);setEditingId(null);setMessage(editingId?"Endringene er lagret som kladd.":"Kladd lagret.");}
 async function publish(id:string){const response=await fetch(`/api/news/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:"published"})});const data=await response.json();if(response.ok)setPosts(posts.map(p=>p.id===id?data.post:p));else setMessage(data.error||"Kunne ikke publisere.");}
 async function weeklyDraft(){const response=await fetch("/api/news/weekly",{method:"POST"});const data=await response.json();if(response.ok){setPosts([data.post,...posts]);setMessage("Ukens Vedi-utkast er laget. Admin må godkjenne publisering.");}else setMessage(data.error||"Kunne ikke lage utkast.");}
 return <div className="news-manager"><section className="studio-panel"><div className="panel-heading"><div><small>{editingId?"REDIGER INNLEGG":"NYTT INNLEGG"}</small><h2>{editingId?"Oppdater kladden":"Start med en kladd"}</h2></div></div><input placeholder="Tittel" value={form.title} onChange={e=>set("title",e.target.value)}/><input placeholder="Kort ingress" value={form.excerpt} onChange={e=>set("excerpt",e.target.value)}/><select value={form.category} onChange={e=>set("category",e.target.value)}><option>Announcements</option><option>Projects</option><option>Guides</option><option>Behind Vedøy</option></select>{!editingId&&<select value={form.authorType} onChange={e=>set("authorType",e.target.value as Form["authorType"])}><option value="user">Skrevet av {authorName}</option><option value="vedi">Skrevet av Vedi · KI</option></select>}<textarea rows={10} placeholder="Skriv innholdet her …" value={form.content} onChange={e=>set("content",e.target.value)}/><button className="button button--dark" type="button" onClick={save}>{editingId?"Lagre endringer":"Lagre som kladd"}</button>{editingId&&<button className="button button--small" type="button" onClick={()=>{setEditingId(null);setForm(empty)}}>Avbryt</button>}{message&&<p>{message}</p>}</section><section className="studio-panel"><div className="panel-heading"><div><small>INNLEGG</small><h2>{posts.length} utkast og publiserte</h2></div><button className="button button--small" type="button" onClick={weeklyDraft}>Lag ukens Vedi-utkast</button></div>{posts.map(post=><article className="news-admin-row" key={post.id}><div><strong>{post.title||"Uten tittel"}</strong><span>{post.category} · {post.status} · {post.authorName}</span></div><div><button className="button button--small" type="button" onClick={()=>{setEditingId(post.id);setForm({title:post.title,excerpt:post.excerpt,content:post.content,category:post.category,authorType:post.authorType})}}>Rediger</button>{post.status==="draft"&&canPublish&&<button className="button button--small button--dark" type="button" onClick={()=>publish(post.id)}>Publiser</button>}</div></article>)}</section></div>;
}
