"use client";
import { useMemo, useState } from "react";
import type { TeamMember, TeamRole } from "@/lib/types";
const roleLabels: Record<TeamRole, string> = { owner: "Eier", admin: "Administrator", manager: "Leder", editor: "Redaktør", member: "Medlem" };
const roles: Exclude<TeamRole, "owner">[] = ["admin", "manager", "editor", "member"];
const defaultTeams = ["Vedøy Studio", "Google Workspace", "Microsoft 365", "Kunde og prosjekt"];
export function TeamHierarchy({ initialMembers, canManage }: { initialMembers: TeamMember[]; canManage: boolean }) {
 const [members,setMembers]=useState(initialMembers); const [dragged,setDragged]=useState<string|null>(null); const [notice,setNotice]=useState(""); const [form,setForm]=useState({name:"",email:"",role:"member" as Exclude<TeamRole,"owner">,teamName:"Vedøy Studio"});
 const teams=useMemo(()=>Array.from(new Set([...defaultTeams,...members.map(member=>member.teamName)])).filter(Boolean),[members]);
 async function patch(id:string,input:{role?:Exclude<TeamRole,"owner">;teamName?:string;sortOrder?:number}){const response=await fetch("/api/team",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...input})});const data=await response.json();if(!response.ok)return setNotice(data.error||"Kunne ikke lagre team eller rolle.");setMembers(items=>items.map(item=>item.id===id?data.member:item).sort((a,b)=>a.teamName.localeCompare(b.teamName)||a.sortOrder-b.sortOrder));setNotice("Endringen er lagret. Tilgang oppdateres ved neste innlogging.");}
 async function add(){const response=await fetch("/api/team",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const data=await response.json();if(!response.ok)return setNotice(data.error||"Kunne ikke legge til medlem.");setMembers(items=>[...items,data.member].sort((a,b)=>a.teamName.localeCompare(b.teamName)||a.sortOrder-b.sortOrder));setForm({name:"",email:"",role:"member",teamName:"Vedøy Studio"});setNotice("Teammedlem er lagt til. Personen får rollen når samme e-post logger inn.");}
 function drop(target:TeamMember){if(!dragged||dragged===target.id)return;const source=members.find(member=>member.id===dragged);if(!source||source.role==="owner"||target.role==="owner"||source.teamName!==target.teamName)return;const team=members.filter(member=>member.teamName===target.teamName);const sourceIndex=team.findIndex(member=>member.id===source.id),targetIndex=team.findIndex(member=>member.id===target.id);team.splice(sourceIndex,1);team.splice(targetIndex,0,source);const reordered=team.map((member,index)=>({...member,sortOrder:(index+1)*10}));setMembers(items=>items.map(member=>reordered.find(item=>item.id===member.id)||member));void Promise.all(reordered.filter(member=>member.role!=="owner").map(member=>patch(member.id,{sortOrder:member.sortOrder})));setDragged(null);}
 return <section className="studio-panel team-hierarchy"><div className="panel-heading"><div><small>TEAM, TJENESTER OG ROLLER</small><h2>Organiser arbeidet i team.</h2></div><span className="team-hierarchy__badge">{canManage?"ADMINISTRATOR":"TEAMOVERSIKT"}</span></div><p>Alle ansatte kan se teamene og hvem de samarbeider med. Administratorer fordeler medarbeidere mellom Vedøy, Google Workspace, Microsoft 365 eller egne kundeteam – og styrer roller innenfor dette.</p><div className="team-hierarchy__teams">{teams.map(team=><section key={team}><header><span>◌</span><div><small>TEAM</small><h3>{team}</h3></div><b>{members.filter(member=>member.teamName===team).length} medlem{members.filter(member=>member.teamName===team).length===1?"":"mer"}</b></header><div className="team-hierarchy__tree">{members.filter(member=>member.teamName===team).length?members.filter(member=>member.teamName===team).map(member=><article draggable={canManage&&member.role!=="owner"} onDragStart={()=>setDragged(member.id)} onDragOver={event=>event.preventDefault()} onDrop={()=>drop(member)} key={member.id} className={member.role==="owner"?"is-owner":""}><span className="team-member-avatar">{member.avatarUrl?<img src={member.avatarUrl} alt=""/>:member.name.slice(0,2).toUpperCase()}</span><div><strong>{member.name}</strong><small>{member.email}</small></div><i>{roleLabels[member.role]}</i>{canManage&&member.role!=="owner"?<><select value={member.teamName} aria-label="Velg team" onChange={event=>patch(member.id,{teamName:event.target.value})}>{teams.map(teamOption=><option value={teamOption} key={teamOption}>{teamOption}</option>)}</select><select value={member.role} aria-label="Velg rolle" onChange={event=>patch(member.id,{role:event.target.value as Exclude<TeamRole,"owner">})}>{roles.map(role=><option value={role} key={role}>{roleLabels[role]}</option>)}</select></>:<b>Beskyttet</b>}</article>):<p className="team-hierarchy__empty">Ingen medlemmer i dette teamet ennå.</p>}</div></section>)}</div>{canManage&&<div className="team-hierarchy__add"><h3>Legg til medarbeider i et team</h3><input placeholder="Navn" value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/><input type="email" placeholder="navn@bedrift.no" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/><select value={form.teamName} onChange={event=>setForm({...form,teamName:event.target.value})}>{teams.map(team=><option value={team} key={team}>{team}</option>)}</select><select value={form.role} onChange={event=>setForm({...form,role:event.target.value as Exclude<TeamRole,"owner">})}>{roles.map(role=><option value={role} key={role}>{roleLabels[role]}</option>)}</select><button className="button button--dark" type="button" onClick={add}>Legg til medlem</button></div>}{notice&&<p className="team-hierarchy__notice">{notice}</p>}</section>;
}
