import Link from "next/link";
import { notFound, redirect } from "next/navigation";
const details: Record<string, { title: string; text: string; points: string[]; image?: { src: string; alt: string }; demoUrl?: string }> = {
  builder: { title: "Vedøy Builder", text: "En rolig byggeflate for profesjonelle nettsider.", points: ["Seksjonsbasert redigering", "Designsystem og temaer", "Forhåndsvisning før publisering"] },
  email: { title: "Vedøy E-post", text: "En samlet Vedøy-innboks for profesjonell e-post.", points: ["Domene-e-post og teaminnboks", "Redigerbare svarmaler", "Varsler og oppfølging"] },
  database: { title: "Vedøy Database", text: "Et oversiktlig og sikkert sted for dataene tjenestene dine bygger på.", points: ["PostgreSQL-prosjekter", "Sikre tilkoblinger og miljøer", "Backup- og statusoversikt"] },
  hosting: { title: "Vedøy Hosting", text: "Kommer snart. Hostingflyten er under utvikling og vises foreløpig som en ikke-bindende forhåndsvisning.", points: ["Planlagt publisering og deploy", "Planlagt DNS, SSL og backup", "Samlet support og drift når tjenesten åpner"] },
  calendar: { title: "Vedøy Calendar", text: "Én samlet kalender for booking, timeregistrering og samordning av Google-, Microsoft- og e-postkalendere.", points: ["Booking og timeregistrering i samme oversikt", "Konfliktkontroll for ansatte, lokasjoner og ressurser", "Planlagt synk mot Google Calendar og Microsoft Calendar"] },
  canvas: { title: "Vedøy Canvas", text: "Et profesjonelt arbeidsrom for virksomheter som vil samle notater, prosjekter, møter og oppgaver på ett sted.", points: ["Notatbøker, seksjoner og sider for hvert prosjekt", "Oppgaver, etiketter, vedlegg og søk", "Deling, versjonshistorikk og sikker lagring i Vedøy Growth"] },
  "omnicart-tycoon": { title: "Omnicart Tycoon", text: "En interaktiv e-commerce simulator der du lærer hvordan produkter, lager, ordre og vekst henger sammen.", points: ["Produkt- og kolleksjonsvalg", "Lager, ordre og marginer", "Scenarioer for vekst og kundereise"], image: { src: "/projects/omnicart-tycoon.jfif", alt: "Omnicart Tycoon e-commerce simulator" }, demoUrl: "https://vedoy-eccomerce-game.vercel.app/" }
};
export function generateStaticParams() { return Object.keys(details).map((slug) => ({ slug })); }
export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; if (slug === "email") redirect("https://mail.vedoystudio.no"); const detail = details[slug]; if (!detail) notFound(); return <section className="project-detail-editorial"><div className="project-detail-editorial__inner"><Link href="/#prosjekter">← Tilbake til Vedøy Studio</Link><p className="editorial-kicker lime">VEDØY STUDIO · UNDER ARBEID</p><h1>{detail.title}<br /><em>kommer steg for steg.</em></h1><p>{detail.text}</p>{detail.image ? <img className="project-detail-editorial__media" src={detail.image.src} alt={detail.image.alt} /> : null}<div><h2>Dette bygger vi</h2><ul>{detail.points.map((point) => <li key={point}>{point}</li>)}</ul></div>{detail.demoUrl ? <a className="editorial-button" href={detail.demoUrl} target="_blank" rel="noreferrer">Åpne Omnicart Tycoon <span>↗</span></a> : null}<Link className="editorial-button" href="/#kontakt">Snakk med oss <span>↗</span></Link></div></section>; }
